name: CI/CD para React

on:
  push:
    branches:
      - main  # Reemplaza "main" con el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v2
      
    - name: Instalar dependencias
      run: npm install
      
    - name: Construir la aplicación
      run: npm run build
      
    #- name: Desplegar a Firebase Hosting
    #  uses: w9jds/firebase-action@v2
    #  with:
    #    args: deploy --only hosting
    #  env:
    #    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
